import type { Metadata } from "next";
import { Geist, Geist_Mono,Genos } from "next/font/google";
import "./globals.css";

const genos = Genos({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Add other weights if needed
  variable: "--font-genos",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={genos.variable}>
      <body className={genos.variable}>
        {children}
      </body>
    </html>
  );
}
